name: AllSigns
main: surva\allsigns\AllSigns
version: 2.0.8
api: 5.0.0

author: survanetwork
description: Turn signs into world teleport and command signs
website: https://dev.surva.net/plugins/#allsigns

permissions:
  allsigns.create:
    description: "Create signs using AllSigns"
    default: op
  allsigns.use:
    description: "Use signs created by AllSigns"
    default: true
